# "Hulk Smash 39.0" (Monolithic) - "Hulk" (v28.0) (GPU)
FROM nvidia/cuda:12.1.0-runtime-ubuntu22.04
RUN apt-get update && apt-get install -y python3.11 python3-pip
WORKDIR /app
RUN pip install --no-cache-dir fastapi uvicorn aiohttp torch transformers accelerate
COPY ./servers/chro_server.py .
CMD ["uvicorn", "chro_server:app", "--host", "0.0.0.0", "--port", "8008"]
