# "Hulk Smash 39.0" (Monolithic) - "Dumb" (v28.0) (CPU)
FROM python:3.11-slim
WORKDIR /app
RUN pip install --no-cache-dir fastapi uvicorn aiohttp
COPY ./servers/docker_proxy.py .
CMD ["uvicorn", "docker_proxy:app", "--host", "0.0.0.0", "--port", "8004"]
